version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"  # Change this to the appropriate port if needed
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # Expose the Redis port
