version: '3'
services:
  app:
    build: .
    ports:
      - "5010:5010"
    depends_on:
      - redis
      - db
    networks:
      - database

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - C:\redis_data:/data
    networks:
      - database

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - C:\postgres_data:/var/lib/postgresql/data
    networks:
      - database

networks:
  database:
    driver: bridge