apiVersion: v1 
kind: Pod
metadata:
  name: vote-app
  labels:
    name: vote-app
    app: voting-app
spec:
  containers:
    - name: vote-app
      image: saiganesh15/votingapp_vote:latest
      ports:
        - containerPort: 5000