apiVersion: v1 
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    name: vote-app
    app: voting-app